[package]
name = "pjatk_council_newsletter"
version = "0.1.0"
edition = "2018"
author = "Rafał Opiłowski <rafalopilowski1@outlook.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
