name: Push latest post

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache timestamp
        uses: actions/cache@v2
        with:
          - path: "~/"
          - key: "timestamp.txt"

      - name: Add Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v1

      - name: Run the bot
        env:
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        run: cargo run --release
