name: Push latest post

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache timestamp
        id: cache-timestamp
        uses: actions/cache@v2
        with:
          path: "timestamp.txt"
          key: "timestamp-${{ hashFiles('timestamp.txt') }}"
          restore-keys: |
            timestamp_
            timestamp

      - name: Add Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v1
      
      - name: Read the file (before)
        if: steps.cache-timestamp.cache-hit == true
        run: cat timestamp.txt
      - name: Run the bot
        env:
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        run: cargo run --release
        
      - name: Read the file (after)
        run: cat timestamp.txt
