name: Push latest post

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: Swatinem/rust-cache@v1
    - name: Run
      env:
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
      run: cargo run --release
